### ISSUE TITLE
Broken by an Express types update

### ISSUE THREAD

**Issue by theFroh** [blakeembrey/async-middleware#20]
G'day, it looks like Express has updated their type definition of `NextFunction` to:
```typescript
export interface NextFunction {
    (err?: any): void;
    /**
     * "Break-out" of a router by calling {next('router')};
     * @see {https://expressjs.com/en/guide/using-middleware.html#middleware.router}
     */
    (deferToNext: "router"): void;
}
```

Which means it is incompatible with the `NextFunction` definition in this module's `index.d.ts`.

I'm working around this myself by explicitly importing `NextFunction` from Express to type the wrapper function.

Cheers!

**Comment by blakeembrey** [comment]
Sounds like the same(?) issue as https://github.com/blakeembrey/async-middleware/issues/19. Feel free to submit a PR, unfortunately I'm not particularly eager to follow `@types/express` and mirror those changes since they aren't related directly to this package - that interface _should_ be compatible with the one defined here so you don't have issues.
